#!/bin/sh -ex

DB_NAME=etherpad
DB_USER=etherpad
DB_PASS=$(mcookie)

NODEAPP=/opt/etherpad-lite

# setup mysql for etherpad
/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

/etc/init.d/mysql stop

# download etherpad and install dependencies
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

cd $(dirname $NODEAPP)
git clone https://github.com/ether/etherpad-lite.git

cd $NODEAPP
./bin/installDeps.sh

unset HTTP_PROXY

# setup etherpad
cat >$NODEAPP/settings.json<<EOF
{
  "ip": "127.0.0.1",
  "port": 8000,

  "dbType": "mysql",
  "dbSettings": {
    "user"    : "$DB_USER",
    "host"    : "localhost",
    "password": "$DB_PASS",
    "database": "$DB_NAME"
  },

  "users": {
    "admin": {
      "password": "turnkey",
      "is_admin": "true"
    }
  },

  "defaultPadText": "Welcome to TurnKey Etherpad Lite!\n\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\n\nRelease notes: http:\/\/www.turnkeylinux.org\/etherpad\n",

  "requireSession": false,
  "editOnly": false,
  "minify": true,
  "maxAge": 21600000, // 6 hours
  "abiword": null,
  "loglevel": "WARN"
}
EOF

echo -n $(mcookie) > $NODEAPP/APIKEY.txt

echo -n "done" > $NODEAPP/src/.ep_initialized
chown nodejs:nodejs $NODEAPP/src/.ep_initialized

cat >/etc/default/nodejs<<EOF
# sourced by /etc/init.d/nodejs
NODEJS_EXEC=$NODEAPP/bin/safeRun.sh
EOF

mkdir -p $NODEAPP/var
chown nodejs:nodejs $NODEAPP
chown -R nodejs:nodejs $NODEAPP/var
chown -R nodejs:nodejs $NODEAPP/node_modules
