#!/bin/sh -ex

DB_NAME=etherpad
DB_USER=etherpad
DB_PASS=$(mcookie)

NODEAPP=/opt/etherpad-lite

# setup mysql for etherpad
service mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"
$MYSQL_BATCH --execute "ALTER DATABASE $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;"

# download etherpad and install dependencies
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

git clone --depth=1 --branch=master https://github.com/ether/etherpad-lite.git $NODEAPP

chown -R node:node $NODEAPP
su node -lc "cd $NODEAPP && ./bin/installDeps.sh"
su - node -c "cd $NODEAPP/src && npm install bcrypt"
su - node -c "cd $NODEAPP/src && npm install bcrypt --save"
su - node -c "cd $NODEAPP && npm install ep_hash_auth"

unset HTTP_PROXY

# default TurnKey Etherpad settings.json (config file) in overlay
mv /usr/local/src/tkl-etherpad.settings.example $NODEAPP/settings.json

echo -n $(mcookie) > $NODEAPP/APIKEY.txt
echo -n $(mcookie) > $NODEAPP/SESSIONKEY.txt
echo -n "done" > $NODEAPP/src/.ep_initialized
mkdir -p $NODEAPP/var

chown -R node:node $NODEAPP

service etherpad start

while :; do [ $(pgrep node) != "" ] && break; sleep 1; done

service etherpad stop

service mysql stop

systemctl enable etherpad

ln -s /etc/nginx/sites-available/nodejs /etc/nginx/sites-enabled/nodejs
