#!/bin/bash -e
# regenerate etherpad secrets and mysql password

. /etc/default/inithooks

NODEAPP=/opt/etherpad
APIKEY=$(mcookie)
PASSWORD=$(mcookie)

echo -n $APIKEY > $NODEAPP/APIKEY.txt

sed -i "s|password.*|password\": \"$PASSWORD\",|" $NODEAPP/settings.json
$INITHOOKS_PATH/bin/mysqlconf.py --user=etherpad --pass="$PASSWORD"

